[package]
name = "lupus-hello"
version = "0.1.0"
description = "Welcome to LupuS"
authors = ["TeknoAnka"]
edition = "2021"

# Bu bloğu ekleyin:
[lib]
name = "lupus_welcome_lib"
path = "src/lib.rs"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-shell = "2.0"
tauri-plugin-autostart = "2.0"
serde = { version = "1.0", features = ["derive"] }
